// Generated by CoffeeScript 1.9.2
(function() {
  var controller, myApp, services;

  angular.module('hardware', ['pascalprecht.translate', 'plugwise.ngSweetAlert', 'ngRoute', 'hardware.filters', 'hardware.services', 'hardware.controllers', 'hardware.directives', 'ngCookies', 'ngDragDrop', 'ui.bootstrap', 'ui.bootstrap.modal']).config(function($translateProvider) {
    return $translateProvider.useStaticFilesLoader({
      prefix: 'translation/',
      suffix: '.json'
    }).preferredLanguage('nl-NL').fallbackLanguage(['en-US']).useLocalStorage();
  }).config(function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    return delete $httpProvider.defaults.headers.common['X-Requested-With'];
  }).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/index/:id*', {
        name: 'Index',
        templateUrl: 'view/index.html'
      });
      $routeProvider.when('/index', {
        name: 'Index',
        templateUrl: 'view/index.html'
      });
      return $routeProvider.otherwise({
        redirectTo: '/index'
      });
    }
  ]).run([
    'JsonService', '$location', function(JsonService, $location) {
      if ($location.path() === '/index' || $location.path() === '') {
        return JsonService.serverRequests('../cache/last/last_connect.pte').then((function(fetch) {
          $location.path("/index/" + fetch.data.replace(/(\r\n|\n|\r)/gm, ""));
        }));
      }
    }
  ]);

  controller = angular.module('hardware.controllers', []);

  controller.controller('HardwareController', function() {});

  controller.controller('languageInit', [
    '$translate', '$scope', function($translate, $scope) {
      $scope.init = function() {
        return $scope.languageSelect = $translate.use();
      };
      $scope.init();
      return $scope.changeLanguage = function() {
        if ($translate.use() !== $scope.changedLanguageIn) {
          return $translate.use($scope.changedLanguageIn);
        }
      };
    }
  ]).controller('AddressIdentifier', [
    '$scope', '$location', '$http', 'JsonService', '$filter', '$route', 'regexValidate', '$timeout', '$window', 'generate', 'SweetAlert', '$translate', function($scope, $location, $http, JsonService, $filter, $route, regexValidate, $timeout, $window, generate, SweetAlert, $translate) {
      var visible;
      $scope.valid = false;
      $scope.windowOpen = false;
      $scope.trigger = {
        'place': 'both'
      };
      $scope.calendar = '';
      visible = '';
      $scope.openclonemenu = function(index) {
        if (visible !== parseInt(index)) {
          visible = parseInt(index);
        } else {
          visible = '';
        }
      };
      $scope.clonecommand = function(index, commandid, id, name) {
        var uuid;
        uuid = generate.uuid();
        JsonService.serverRequests('../connect/clonecommand.pte?new_uuid=' + uuid + '&name=' + name + '&clone_to_id=' + id + '&clone_command_id=' + commandid + '&clone_from_id=' + $scope.identifier + '&clone_from_ip=' + $scope.ip).then((function(fetch) {
          $translate(["successfully", "coolding_command_cloned"]).then(function(translations) {
            return SweetAlert.swal(translations.successfully, translations.coolding_command_cloned, "success");
          });
        }));
        visible = '';
      };
      $scope.clonemenu = function(index) {
        if (visible === parseInt(index)) {
          return true;
        } else {
          return false;
        }
      };
      $scope.closeclonemenu = function() {
        visible = '';
      };
      $scope.runScript = function() {
        if ($scope.run === false) {
          $scope.run = true;
          return $scope.running();
        } else {
          return $scope.run = false;
        }
      };
      $window.saveCalendarParent = function(id, filepath, filename) {
        $scope.calendar = id + '_' + filepath;
        $scope.calendarname = filename;
        $scope.$apply();
      };
      $window.getTranslationsCalendar = function() {
        return $translate(["calendar", "save_calendar_exception", "schema", "exception_days", "close", "history", "mon", "tue", "wed", "thur", "fri", "sat", "sun", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sept", "oct", "nov", "dec", "calendar_saved", "calendar_reset", "calendar_exception", "calendar_return", "calendar_remove", "calendar_give_name", "calendar_select_load"]).then(function(translations) {
          return translations;
        });
      };
      $scope.removeCalendar = function() {
        $scope.calendarname = '';
        $scope.calendar = '';
      };
      $scope.modifyexception = function(id) {
        var child, interval;
        child = void 0;
        interval = void 0;
        $scope.windowOpen = true;
        child = $window.open('calendar.html?id=' + id, '_blank', 'height=600,width=1000');
        return interval = setInterval((function() {
          var _error;
          try {
            (function() {
              if (child.document.domain === document.domain) {
                return clearInterval(interval);
              }
            });
          } catch (_error) {
            _error = _error;
            clearInterval(interval);
            $scope.windowOpen = false;
          }
        }), 500);
      };
      $scope.remove = function(id, extraValue) {
        var deviceid, filename;
        filename = '';
        deviceid = '';
        angular.forEach($scope.history, function(v, k) {
          if (v.sedid != null) {
            if (v.sedid === id) {
              filename = v.filename;
              deviceid = v.sedid;
              $scope.history.splice(k, 1);
            }
          }
        });
        JsonService.serverRequests('../connect/save_coolding_setting.pte', 'POST', JSON.stringify($scope.history)).then((function(fetch) {}));
        return JsonService.serverRequests('../connect/coolding_editEvent.pte?filename=' + filename + '&id=' + deviceid + '&extravalue=' + extraValue + '&remove=true&status=false').then((function(fetch) {}));
      };
      $scope.turnOff = function(id, extraValue) {
        var deviceid, filename, status;
        filename = '';
        deviceid = '';
        status = false;
        angular.forEach($scope.history, function(v, k) {
          if (v.sedid != null) {
            if (v.sedid === id) {
              if (v.running === true) {
                $scope.history[k].running = false;
              } else {
                $scope.history[k].running = true;
              }
              status = $scope.history[k].running;
              filename = v.filename;
              deviceid = v.sedid;
            }
          }
        });
        JsonService.serverRequests('../connect/save_coolding_setting.pte', 'POST', JSON.stringify($scope.history)).then((function(fetch) {}));
        return JsonService.serverRequests('../connect/coolding_editEvent.pte?filename=' + filename + '&id=' + deviceid + '&extravalue=' + extraValue + '&status=' + status).then((function(fetch) {}));
      };
      $scope.reset = function() {
        $scope.first_command = '';
        $scope.oursed = '';
        $scope.second_command = '';
        $scope.third_command = '';
        $scope.fourth_command = '';
        $scope.first_command = {};
        $scope.oursed = {};
        $scope.second_command = {};
        $scope.third_command = {};
        $scope.fourth_command = {};
        $scope.chosen_schedule = {};
        $scope.removeCalendar();
        return JsonService.serverRequests('../connect/schedules.pte').then((function(fetch) {
          $scope.schedules = fetch.data;
          return $scope.chosen_schedule = $scope.schedules[0].uuid;
        }));
      };
      $scope.schedules = '';
      $scope.loadAllSchedules = function() {
        return JsonService.serverRequests('../connect/schedules.pte').then((function(fetch) {
          return $scope.schedules = fetch.data;
        }));
      };
      $scope.loadSchedule = function(uuid) {
        $scope.schedule_loader = true;
        return JsonService.serverRequests('../connect/schedule_values.pte?uuid=' + uuid).then((function(fetch) {
          return $scope.schedule = fetch.data;
        }));
      };
      $scope.log = function() {
        var data, extraValue, filename, sedname;
        filename = Math.floor(Math.random() * 900000) + 10000;
        extraValue = '';
        if ($scope.oursed.type === '3') {
          extraValue = $scope.trigger.place;
        }
        if ($scope.oursed.type === '5') {
          extraValue = "Sense&upper_limit=" + $scope.upper_limit + "&lower_limit=" + $scope.lower_limit + "&schedule=" + $scope.chosen_schedule + "&eco_on=" + $scope.third_command.id + "&eco_off=" + $scope.fourth_command.id;
        }
        JsonService.serverRequests('../connect/coolding_writeScript.pte?id=' + $scope.identifier + '&device=' + $scope.oursed.type + '&extra=' + extraValue + '&ip=' + $scope.ip + '&sequence_id=' + $scope.first_command.id + '&sequence_id_off=' + $scope.second_command.id + '&sed_id=' + $scope.oursed.deviceid + '&name=' + filename + '&calendar=' + $scope.calendar, 'jsonp').then((function(fetch) {}));
        if ($scope.oursed.id != null) {
          angular.forEach($scope.history, function(v, k) {
            if (v.sedid != null) {
              if ($scope.oursed.type === '3') {
                if ($scope.trigger.place === 'right') {
                  if (v.sedid === $scope.oursed.id + '_right') {
                    $scope.history.splice(k, 1);
                  }
                }
                if ($scope.trigger.place === 'left') {
                  if (v.sedid === $scope.oursed.id + '_left') {
                    $scope.history.splice(k, 1);
                  }
                }
                if ($scope.trigger.place === 'both') {
                  if (v.sedid === $scope.oursed.id + '_left') {
                    $scope.history.splice(k, 1);
                  }
                  if (v.sedid === $scope.oursed.id + '_right') {
                    return $scope.history.splice(k, 1);
                  }
                }
              } else {
                if (v.sedid === $scope.oursed.id) {
                  return $scope.history.splice(k, 1);
                }
              }
            }
          });
          if ($scope.oursed.title != null) {
            sedname = $scope.oursed.title;
          } else {
            sedname = 'No name';
          }
          if ($scope.oursed.type === '3') {
            if ($scope.trigger.place === 'both') {
              data = [
                {
                  "filename": filename,
                  "running": true,
                  "extravalue": "right",
                  "command1": $scope.first_command.id,
                  "commandname1": $scope.first_command.title,
                  "command2": $scope.second_command.id,
                  "commandname2": $scope.second_command.title,
                  "seddeviceid": $scope.oursed.type,
                  "sedid": $scope.oursed.id + "_right"
                }, {
                  "filename": filename,
                  "running": true,
                  "extravalue": "left",
                  "command1": $scope.first_command.id,
                  "commandname1": $scope.first_command.title,
                  "command2": $scope.second_command.id,
                  "commandname2": $scope.second_command.title,
                  "seddeviceid": $scope.oursed.type,
                  "sedid": $scope.oursed.id + "_left"
                }
              ];
            } else {
              data = [
                {
                  "filename": filename,
                  "running": true,
                  "extravalue": $scope.trigger.place,
                  "command1": $scope.first_command.id,
                  "commandname1": $scope.first_command.title,
                  "command2": $scope.second_command.id,
                  "commandname2": $scope.second_command.title,
                  "seddeviceid": $scope.oursed.type,
                  "sedid": $scope.oursed.id + "_" + $scope.trigger.place
                }
              ];
            }
          } else if ($scope.oursed.type === '5') {
            data = [
              {
                "filename": filename,
                "running": true,
                "command1": $scope.first_command.id,
                "commandname1": $scope.first_command.title,
                "command2": $scope.second_command.id,
                "commandname2": $scope.second_command.title,
                "command3": $scope.third_command.id,
                "commandname3": $scope.third_command.title,
                "command4": $scope.fourth_command.id,
                "commandname4": $scope.fourth_command.title,
                "upper_limit": $scope.upper_limit,
                "lower_limit": $scope.lower_limit,
                "schedule": $scope.chosen_schedule,
                "seddeviceid": $scope.oursed.type,
                "sedid": $scope.oursed.id,
                "sed_id": $scope.oursed.deviceid,
                "calendar_path": $scope.calendar,
                "calendar_name": $scope.calendarname,
                "schema_id": $scope.chosen_schedule
              }
            ];
          } else {
            data = [
              {
                "filename": filename,
                "running": true,
                "command1": $scope.first_command.id,
                "commandname1": $scope.first_command.title,
                "command2": $scope.second_command.id,
                "commandname2": $scope.second_command.title,
                "seddeviceid": $scope.oursed.type,
                "sedid": $scope.oursed.id
              }
            ];
          }
          if ($scope.history != null) {
            $scope.history = $scope.history.concat(data);
          } else {
            $scope.history = data;
          }
          $scope.tmphistory = [];
          angular.forEach($scope.history, function(v, k) {
            $scope.tmphistory[k] = [];
            return JsonService.serverRequests('../connect/source_get_name.pte?id=' + v.sedid.replace(/_left|_right/g, '')).then((function(fetch) {
              $scope.tmphistory[k]["sedname"] = fetch.data;
            }), function(reason) {
              $scope.tmphistory[k]["sedname"] = '';
            });
          });
          return JsonService.serverRequests('../connect/save_coolding_setting.pte', 'POST', JSON.stringify($scope.history)).then((function(fetch) {
            $translate(["successfully", "command_generated"]).then(function(translations) {
              return SweetAlert.swal(translations.successfully, translations.command_generated, "success");
            });
            $scope.reset();
          }));
        }
      };
      $scope.emptyList = function(id) {
        if (id === 1) {
          $scope.first_command = '';
          $scope.first_command = {};
        }
        if (id === 2) {
          $scope.oursed = '';
          $scope.oursed = {};
          $scope.third_command = '';
          $scope.third_command = {};
          $scope.fourth_command = '';
          $scope.fourth_command = {};
        }
        if (id === 3) {
          $scope.second_command = '';
          $scope.second_command = {};
        }
        if (id === 4) {
          $scope.third_command = '';
          $scope.third_command = {};
        }
        if (id === 5) {
          $scope.fourth_command = '';
          return $scope.fourth_command = {};
        }
      };
      $scope.placeSed = function(id, type, deviceid) {
        var idr;
        idr = id.split("_");
        if (idr[1] != null) {
          $scope.trigger = {
            'place': idr[1]
          };
        }
        id = id.replace("_right", "");
        id = id.replace("_left", "");
        $scope.oursed.id = id;
        $scope.oursed.type = type;
        JsonService.serverRequests('../connect/source_get_name.pte?id=' + id.replace(/_left|_right/g, '')).then((function(fetch) {
          $scope.oursed.title = fetch.data;
        }), function(reason) {
          $scope.oursed.title = '';
        });
        return $scope.oursed.deviceid = deviceid;
      };
      $scope.placeCooldingcom = function(id, title) {
        var open;
        open = false;
        if ($scope.first_command.id == null) {
          open = true;
          $scope.first_command.id = id;
          $scope.first_command.title = title;
        }
        if (($scope.second_command.id == null) && !open) {
          open = true;
          $scope.second_command.id = id;
          $scope.second_command.title = title;
        }
        if ($scope.oursed.type === '5') {
          if (($scope.third_command.id == null) && !open) {
            open = true;
            $scope.third_command.id = id;
            $scope.third_command.title = title;
          }
          if (($scope.fourth_command.id == null) && !open) {
            open = true;
            $scope.fourth_command.id = id;
            return $scope.fourth_command.title = title;
          }
        }
      };
      $scope.load_sed = function(sed) {
        var sed_id;
        $scope.sed_loading = true;
        sed_id = 6;
        if (sed === 'switch') {
          sed_id = 3;
        }
        if (sed === 'scan') {
          sed_id = 6;
        }
        if (sed === 'sense') {
          sed_id = 5;
        }
        return JsonService.serverRequests('../connect/modules_json.pte?module=' + sed_id).then((function(fetch) {
          return JsonService.serverRequests('../cache/modules.json').then((function(fetch) {
            $scope.loader_status = false;
            $scope.button_status = false;
            $scope.error_status = false;
            $scope.sed_loading = false;
            $scope.devices.statuses = fetch.data;
            $scope.devices.statuses.show = true;
          }), function(reason) {
            $scope.loader_status = true;
            $scope.button_status = true;
            $scope.error_status = true;
          });
        }));
      };
      $scope.sendCooldingCommand = function(command) {
        return JsonService.serverRequests('../connect/sendcooldingcommand.pte?command=' + command + '&id=' + $scope.identifier + '&ip=' + $scope.ip).then((function(result) {}), function(reason) {});
      };
      $scope.cooldingSequence = function(identifier) {
        $scope.reload = 'Loading...';
        $translate(["loading"]).then(function(translations) {
          return $scope.reload = translations.loading;
        });
        return $.get('../connect/coolding_sequences.pte?ip=' + $scope.ip + '&id=' + identifier, function(xmls) {
          if (xmls === 'ok') {
            JsonService.serverRequests('../cache/coolding_sequences.xml').then((function(xmll) {
              var jsonn;
              $scope.loader_current = false;
              $scope.error_current = false;
              if (xmll != null) {
                jsonn = $.xml2json(xmll.data);
                $scope.devices.current = jsonn.sequences;
                if ($scope.devices.current != null) {
                  $scope.devices.current.show = true;
                }
                $scope.reload = 'Reload';
                $translate(["reload"]).then(function(translations) {
                  return $scope.reload = translations.reload;
                });
              }
            }), function(reason) {});
          } else {
            if ($scope.ip === $scope.wifiip) {
              if ($scope.lanip != null) {
                $scope.ip = $scope.lanip;
                $scope.cooldingSequence(identifier);
              }
            } else {
              if ($scope.wifiip != null) {
                $scope.ip = $scope.wifiip;
                $scope.cooldingSequence(identifier);
              }
            }
          }
        });
      };
      $scope.cooldingInfo = function(identifier) {
        $scope.reload = 'Loading...';
        $translate(["loading"]).then(function(translations) {
          return $scope.reload = translations.loading;
        });
        return $.get('../connect/coolding_info.pte?ip=' + $scope.ip + '&id=' + identifier, function(xml) {
          var error;
          if (xml === 'ok') {
            $scope.loadLatest();
            JsonService.serverRequests('../cache/coolding_info.xml').then((function(xmll) {
              var json;
              $scope.cooldingSequence(identifier);
              if (xmll != null) {
                json = $.xml2json(xmll.data);
                $scope.coolding_name = json.info;
              }
            }), function(reason) {});
          } else {
            error = true;
            if ($scope.ip === $scope.wifiip) {
              if ($scope.lanip != null) {
                error = false;
                $scope.ip = $scope.lanip;
                $scope.cooldingInfo(identifier);
              }
            } else {
              if ($scope.wifiip != null) {
                error = false;
                $scope.ip = $scope.wifiip;
                $scope.cooldingInfo(identifier);
              }
            }
            if (error) {
              $translate(["error_coolding_not_found", "error_coolding_not_connect"]).then(function(translations) {
                return SweetAlert.swal(translations.error_coolding_not_found, translations.error_coolding_not_connect, "error");
              });
              $scope.loader_current = false;
              $scope.error_current = true;
            }
          }
        });
      };
      $scope.emptyDevices = function() {
        return $scope.devices = {};
      };
      $scope.load_history = function(h) {
        return angular.forEach($scope.history, function(v, k) {
          var count_schedule;
          if (v.sedid === h) {
            $scope.placeSed(v.sedid, v.seddeviceid, v.sed_id);
            if (v.command1 != null) {
              $scope.first_command.id = v.command1;
              $scope.first_command.title = v.commandname1;
            }
            if (v.command2 != null) {
              $scope.second_command.id = v.command2;
              $scope.second_command.title = v.commandname2;
            }
            if (v.command3 != null) {
              $scope.third_command.id = v.command3;
              $scope.third_command.title = v.commandname3;
            }
            if (v.command4 != null) {
              $scope.fourth_command.id = v.command4;
              $scope.fourth_command.title = v.commandname4;
            }
            if (v.upper_limit != null) {
              $scope.upper_limit = v.upper_limit;
              $scope.advanced = true;
            }
            if (v.lower_limit != null) {
              $scope.lower_limit = v.lower_limit;
              $scope.advanced = true;
            }
            if (v.schedule != null) {
              $scope.calendarname = v.calendar_name;
              $scope.calendar = v.calendar_path;
              count_schedule = 0;
              return angular.forEach($scope.schedules, function(i, l) {
                if (i.uuid === v.schedule) {
                  $scope.chosen_schedule = $scope.schedules[count_schedule].uuid;
                }
                return count_schedule += 1;
              });
            }
          }
        });
      };
      $scope.loadLatest = function() {
        return JsonService.serverRequests('../connect/coolding_latest.pte').then((function(fetch) {
          return JsonService.serverRequests('../cache/last/latest_places.json').then((function(fetch) {
            $scope.devices.latest = fetch.data;
          }), function(reason) {});
        }));
      };
      $scope.emptyDevices();
      $scope.loadLatest();
      $scope.request = function(identifier) {
        var devices;
        if (identifier === void 0) {
          return;
        }
        if ($location.path() !== '/index/' + identifier) {
          $location.path('/index/' + identifier);
          return;
        }
        $scope.devices = {};
        $scope.emptyDevices();
        $scope.loadLatest();
        $scope.loading = true;
        if (identifier == null) {
          $scope.devices.error = true;
          $scope.loading = false;
          $scope.error_message = "The MAC-address, UUID or shortid can not be empty.";
          return $translate(["error_empty_id"]).then(function(translations) {
            return $scope.error_message = translations.error_empty_id;
          });
        } else {
          if (!$scope.valid) {
            $scope.devices.error = true;
            $scope.loading = false;
            $scope.error_message = "The MAC-address, UUID or shortid is not valid.";
            return $translate(["error_invalid_id"]).then(function(translations) {
              return $scope.error_message = translations.error_invalid_id;
            });
          } else {
            identifier = identifier.toLowerCase();
            $scope.identifier = identifier;
            if (identifier.toUpperCase().match(/^([0-9A-F]{12})$/)) {
              identifier = identifier.replace(/(.)(.)(?!$)/g, '$1$2:');
            }
            devices = function(callback) {
              JsonService.serverRequests('https://auth.plugwise.net/announce/' + identifier + '.json?callback=JSON_CALLBACK', 'jsonp').then((function(fetch) {
                var lan_ip;
                lan_ip = '';
                if ((fetch.data.lan_ip != null)) {
                  lan_ip = Object.keys(fetch.data.lan_ip);
                }
                if (lan_ip.length === 0) {
                  $scope.ip = fetch.data.wifi_ip;
                  $scope.wifiip = fetch.data.wifi_ip;
                } else {
                  $scope.ip = fetch.data.lan_ip;
                  if ((fetch.data.lan_ip != null)) {
                    $scope.wifiip = fetch.data.wifi_ip;
                  }
                  $scope.lanip = fetch.data.lan_ip;
                }
                $scope.loader_device = false;
                $scope.error_device = false;
                JsonService.serverRequests('../connect/plugincheck.pte').then((function(plugin) {
                  if (plugin.data === 'true') {
                    return JsonService.serverRequests('../connect/writable.pte').then((function(writable) {
                      if (writable.data === 'true') {
                        $scope.devices.show = true;
                        $scope.devices.devices = fetch.data;
                        return callback(true);
                      } else {
                        $scope.loader_device = false;
                        $scope.error_device = true;
                        $scope.loading = false;
                        $scope.devices.error = true;
                        $scope.error_message = '';
                        $scope.write_permissions = true;
                        return callback(false);
                      }
                    }));
                  } else {
                    $scope.loader_device = false;
                    $scope.error_device = true;
                    $scope.devices.error = true;
                    $scope.error_message = '';
                    $scope.license_missing = true;
                    return callback(false);
                  }
                }));
                return callback(false);
              }), function(reason) {
                $scope.devices.show = false;
                $scope.loader_device = false;
                $scope.error_device = true;
                $scope.devices.error = true;
                $scope.error_message = "The MAC-address, UUID or shortid can not be found. This could be due to a problem with your Internet connection.";
                $translate(["error_not_found"]).then(function(translations) {
                  return $scope.error_message = translations.error_not_found;
                });
                $scope.loading = false;
                return callback(false);
              });
              return callback(false);
            };
            return devices((function(_this) {
              return function(found) {
                var orderBy;
                if (found) {
                  $scope.loader_current = true;
                  $scope.loader_status = true;
                  $scope.loading = false;
                  $scope.button_status = true;
                  orderBy = $filter('orderBy');
                  $scope.error_current = false;
                  $scope.third_command = {};
                  $scope.fourth_command = {};
                  $scope.second_command = {};
                  $scope.oursed = {};
                  $scope.first_command = {};
                  $scope.lower_limit = 0;
                  $scope.upper_limit = 0;
                  $scope.chosen_schedule = {};
                  $.get('../cache/coolding_setting.json', function(settings) {
                    $scope.history = angular.fromJson(settings);
                    $scope.tmphistory = [];
                    return angular.forEach($scope.history, function(v, k) {
                      $scope.tmphistory[k] = [];
                      return JsonService.serverRequests('../connect/source_get_name.pte?id=' + v.sedid.replace(/_left|_right/g, '')).then((function(fetch) {
                        $scope.tmphistory[k]["sedname"] = fetch.data;
                      }), function(reason) {
                        $scope.tmphistory[k]["sedname"] = '';
                      });
                    });
                  });
                  JsonService.serverRequests('../connect/schedules.pte').then((function(fetch) {
                    $scope.schedules = fetch.data;
                    return $scope.chosen_schedule = $scope.schedules[0].uuid;
                  }));
                  JsonService.serverRequests('../connect/modules_json.pte').then((function(fetch) {
                    return JsonService.serverRequests('../cache/modules.json').then((function(fetch) {
                      $scope.loader_status = false;
                      $scope.button_status = false;
                      $scope.error_status = false;
                      $scope.sed_loading = false;
                      $scope.devices.statuses = fetch.data;
                      $scope.devices.statuses.show = true;
                    }), function(reason) {
                      $scope.loader_status = true;
                      $scope.button_status = true;
                      $scope.error_status = true;
                    });
                  }));
                  $scope.show_last = false;
                  $scope.cooldingInfo(identifier);
                  $scope.order = function(predicate, reverse) {
                    if (predicate === 'last_only') {
                      if ($scope.show_last === false) {
                        $scope.show_last = true;
                        $scope.devices.backup_statuses = $scope.devices.statuses;
                        $scope.devices.statuses = $filter('filterLast')($scope.devices.statuses);
                        $scope.devices.statuses = orderBy($scope.devices.statuses, 'created_date', true);
                        $scope.orderType = 'date';
                        $scope.reverse = true;
                      } else {
                        $scope.show_last = false;
                        $scope.devices.statuses = $scope.devices.backup_statuses;
                      }
                    }
                    $scope.preOrder = predicate;
                    $scope.devices.statuses = orderBy($scope.devices.statuses, predicate, reverse);
                    return $scope.devices.statuses.show = true;
                  };
                  $scope.preOrder = 'name';
                  return $scope.orderByType = function() {
                    if ($scope.preOrder === "name") {
                      $scope.preOrder = 'created_date';
                      return $scope.active = true;
                    } else {
                      $scope.preOrder = 'name';
                      return $scope.active = false;
                    }
                  };
                }
              };
            })(this));
          }
        }
      };
      if ($route.current.params.id != null) {
        $scope.identifier = $route.current.params.id;
        if (regexValidate.checkAll($route.current.params.id)) {
          $location.path('/index/' + $route.current.params.id);
          $scope.valid = true;
          return $scope.request($route.current.params.id);
        }
      }
    }
  ]);

  myApp = angular.module('hardware.directives', []).directive('addressBar', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/address.html'
    };
  }).directive('cooldingInfo', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/coolding-info.html'
    };
  }).directive('changeLanguage', function() {
    return function(scope, element, attrs) {
      return element.bind('click', function() {
        scope.changedLanguageIn = attrs.data;
        return scope.$apply("changeLanguage()");
      });
    };
  }).directive('cooldingRecords', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/coolding-records.html'
    };
  }).directive('historyBlock', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/history.html'
    };
  }).directive('loadSeds', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/load-seds.html'
    };
  }).directive('dragDrop', function() {
    return {
      restrict: "A",
      templateUrl: 'view/blocks/drag-drop.html'
    };
  }).directive('logoutButton', function() {
    return {};
  }).directive("dragingDrop", function($parse) {
    return function(scope, element, attrs) {
      $(element[0]).sortable({
        handle: ".draghandle",
        items: ".dropblock",
        appendTo: element[0],
        start: function(event, ui) {},
        stop: function(event, ui) {
          var i;
          i = 0;
          $("#blocks li").each(function(v, k) {
            console.log(v);
            return console.log(k);
          });
        }
      });
    };
  }).directive('sendCommand', function($parse) {
    return function(scope, element, attrs) {
      var fn;
      fn = $parse(attrs.ngRightClick);
      element.bind('mousedown', function(e) {
        e.stopPropagation();
        if (e.button === 0) {
          scope.$apply(function() {
            scope.sendCooldingCommand(attrs.sendId);
            return false;
          });
          return;
        }
        if (e.button === 2) {
          scope.$apply(function() {
            scope.openclonemenu(attrs.sendIndex);
          });
          return;
        }
      });
      element.bind('contextmenu', function(e) {
        return false;
      });
    };
  }).directive('checkValidid', [
    'regexValidate', function(regexValidate) {
      return function(scope, element) {
        ({
          restrict: "A"
        });
        return element.on('keyup', function(e) {
          scope.$apply(function() {
            return scope.valid = false;
          });
          if (regexValidate.checkAll(e.currentTarget.value)) {
            scope.$apply(function() {
              return scope.valid = true;
            });
          }
          if (e.keyCode === 13) {
            return scope.$apply(function() {
              return scope.request(e.currentTarget.value);
            });
          }
        });
      };
    }
  ]);

  angular.module('hardware.filters', []).filter("momentjs", function() {
    return function(val) {
      return moment(val).format('llll');
    };
  }).filter("tohtml", function($sce) {
    return function(val) {
      if (val != null) {
        console.log(val);
        return $sce.trustAsHtml(val);
      } else {
        return $sce.trustAsHtml('');
      }
    };
  }).filter("shortenid", function() {
    return function(val) {
      return val.substring(0, 8) + '..';
    };
  }).filter("getaddress", function() {
    return function(val) {
      return val.substring(8);
    };
  }).filter("filterLast", function() {
    return function(a) {
      var b, d, e, id, j, len, v;
      v = [];
      d = {};
      for (j = 0, len = a.length; j < len; j++) {
        b = a[j];
        if (d[b.type] != null) {
          if (!moment(d[b.type].created_date).isAfter(b.created_date)) {
            d[b.type] = {
              type: b.type,
              description: b.description,
              created_date: b.created_date
            };
          }
        } else {
          d[b.type] = {
            type: b.type,
            description: b.description,
            created_date: b.created_date
          };
        }
      }
      for (id in d) {
        e = d[id];
        v.push(e);
      }
      return v;
    };
  }).factory("regexValidate", function() {
    this.shortid = (function(_this) {
      return function(v) {
        if (v.toLowerCase().match(/^[b-df-hj-np-tv-xz]{8}$/)) {
          return true;
        }
        return false;
      };
    })(this);
    this.checkAll = (function(_this) {
      return function(v) {
        if (_this.shortid(v)) {
          return true;
        }
        return false;
      };
    })(this);
    return this;
  }).factory("generate", function() {
    this.s8 = (function(_this) {
      return function() {
        return Math.floor((1 + Math.random()) * 0x100000000).toString(16).substring(1);
      };
    })(this);
    this.uuid = (function(_this) {
      return function() {
        return _this.s8() + _this.s8() + _this.s8() + _this.s8();
      };
    })(this);
    return this;
  }).factory("logoutButton", [
    "$rootScope", function($rootScope) {
      this.logoutButton = true;
      this.showButton = (function(_this) {
        return function() {
          return _this.logoutButton = true;
        };
      })(this);
      this.hideButton = (function(_this) {
        return function() {
          return _this.logoutButton = false;
        };
      })(this);
      this.GetStatus = (function(_this) {
        return function() {
          return _this.logoutButton;
        };
      })(this);
      return this;
    }
  ]).factory("Base64", function() {
    var keyStr;
    keyStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
    return {
      encode: function(input) {
        var chr1, chr2, chr3, enc1, enc2, enc3, enc4, i, output;
        output = "";
        chr1 = void 0;
        chr2 = void 0;
        chr3 = "";
        enc1 = void 0;
        enc2 = void 0;
        enc3 = void 0;
        enc4 = "";
        i = 0;
        while (true) {
          chr1 = input.charCodeAt(i++);
          chr2 = input.charCodeAt(i++);
          chr3 = input.charCodeAt(i++);
          enc1 = chr1 >> 2;
          enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
          enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
          enc4 = chr3 & 63;
          if (isNaN(chr2)) {
            enc3 = enc4 = 64;
          } else {
            if (isNaN(chr3)) {
              enc4 = 64;
            }
          }
          output = output + keyStr.charAt(enc1) + keyStr.charAt(enc2) + keyStr.charAt(enc3) + keyStr.charAt(enc4);
          chr1 = chr2 = chr3 = "";
          enc1 = enc2 = enc3 = enc4 = "";
          if (!(i < input.length)) {
            break;
          }
        }
        return output;
      },
      decode: function(input) {
        var base64test, chr1, chr2, chr3, enc1, enc2, enc3, enc4, i, output;
        output = "";
        chr1 = void 0;
        chr2 = void 0;
        chr3 = "";
        enc1 = void 0;
        enc2 = void 0;
        enc3 = void 0;
        enc4 = "";
        i = 0;
        base64test = /[^A-Za-z0-9\+\/\=]/g;
        if (base64test.exec(input)) {
          window.alert("There were invalid base64 characters in the input text.\n" + "Valid base64 characters are A-Z, a-z, 0-9, '+', '/',and '='\n" + "Expect errors in decoding.");
        }
        input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");
        while (true) {
          enc1 = keyStr.indexOf(input.charAt(i++));
          enc2 = keyStr.indexOf(input.charAt(i++));
          enc3 = keyStr.indexOf(input.charAt(i++));
          enc4 = keyStr.indexOf(input.charAt(i++));
          chr1 = (enc1 << 2) | (enc2 >> 4);
          chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
          chr3 = ((enc3 & 3) << 6) | enc4;
          output = output + String.fromCharCode(chr1);
          if (enc3 !== 64) {
            output = output + String.fromCharCode(chr2);
          }
          if (enc4 !== 64) {
            output = output + String.fromCharCode(chr3);
          }
          chr1 = chr2 = chr3 = "";
          enc1 = enc2 = enc3 = enc4 = "";
          if (!(i < input.length)) {
            break;
          }
        }
        return output;
      }
    };
  });

  angular.module('plugwise.ngSweetAlert', []).factory('SweetAlert', [
    '$rootScope', function($rootScope) {
      var self, swal;
      swal = window.swal;
      self = {
        swal: function(arg1, arg2, arg3) {
          $rootScope.$evalAsync(function() {
            if (typeof arg2 === 'function') {
              swal(arg1, (function(isConfirm) {
                $rootScope.$evalAsync(function() {
                  arg2(isConfirm);
                });
              }), arg3);
            } else {
              swal(arg1, arg2, arg3);
            }
          });
        },
        success: function(title, message) {
          $rootScope.$evalAsync(function() {
            swal(title, message, 'success');
          });
        },
        error: function(title, message) {
          $rootScope.$evalAsync(function() {
            swal(title, message, 'error');
          });
        },
        warning: function(title, message) {
          $rootScope.$evalAsync(function() {
            swal(title, message, 'warning');
          });
        },
        info: function(title, message) {
          $rootScope.$evalAsync(function() {
            swal(title, message, 'info');
          });
        }
      };
      return self;
    }
  ]);

  "use strict";

  services = angular.module('hardware.services', []);

  services.service("JsonService", [
    "$http", "$q", "$rootScope", function($http, $q, $rootScope) {
      var PLUGWISECLOUD, headers;
      PLUGWISECLOUD = "";
      headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, GET, OPTIONS, PUT',
        'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      };
      this.serverRequests = function(url, method, data, server) {
        var deferred;
        if (method == null) {
          method = 'GET';
        }
        if (data == null) {
          data = {};
        }
        if (server == null) {
          server = PLUGWISECLOUD;
        }
        deferred = $q.defer();
        if (method === 'jsonp') {
          return $http.jsonp(url).success(function(json) {
            deferred.resolve(json.data);
          }).error(function(err) {
            deferred.reject(err);
            return deferred.promise;
          });
        } else {
          return $http({
            headers: headers,
            url: url,
            method: method,
            dataType: 'json',
            data: data
          }).success(function(json) {
            deferred.resolve(json.data);
          }).error(function(err) {
            deferred.reject(err);
            return deferred.promise;
          });
        }
      };
      return this;
    }
  ]).service("AuthenticationsService", [
    "$http", "Base64", "$rootScope", "$cookieStore", "JsonService", "$location", function($http, Base64, $rootScope, $cookieStore, JsonService, $location) {
      var service;
      service = {};
      this.AddBasicAuth = function(username, password) {
        return $http.defaults.headers.common["Authorization"] = "Basic " + Base64.encode(username + ":" + password);
      };
      this.Status = function(callback) {
        JsonService.serverRequests('').then(((function(_this) {
          return function(fetch) {
            return callback({
              'loggedin': true
            });
          };
        })(this)), function(reason) {
          return callback({
            'loggedin': false
          });
        });
      };
      this.TryConnection = function(username, password, callback) {
        JsonService.serverRequests('').then(((function(_this) {
          return function(fetch) {
            _this.SetCredentials(username, password);
            $location.path("/index");
            return callback({
              'loggedin': true
            });
          };
        })(this)), function(reason) {
          callback("401");
          return {
            'loggedin': false
          };
        });
      };
      this.SetCredentials = function(username, password) {
        this.AddBasicAuth(username, password);
        $rootScope.globals = {
          currentUser: {
            username: username,
            authdata: Base64.encode(username + ":" + password)
          }
        };
        $cookieStore.put("globals", $rootScope.globals);
      };
      this.ClearCredentials = function() {
        $rootScope.globals = {};
        $cookieStore.remove("globals");
        $http.defaults.headers.common.Authorization = "Basic ";
      };
      return this;
    }
  ]);

}).call(this);
